### ISSUE TITLE
Upgrade gatsby to v3

### ISSUE THREAD

**Issue by malnajdi** [sharektech/sharektech.com#8]
This is to document all issues that will be faced while upgrading to v3

**Comment by ahmedalmulla** [comment]
I got an error when we I run the build:

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/usr/src/app/www/node_modules/postcss/lib/processor.es6:117:15)
    at new Processor (/usr/src/app/www/node_modules/postcss/lib/processor.es6:38:25)
    at postcss (/usr/src/app/www/node_modules/postcss/lib/postcss.es6:34:10)
    at Object.loader (/usr/src/app/www/node_modules/postcss-loader/dist/index.js:87:20)

For more details see https://gatsby.dev/issue-how-to

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/usr/src/app/www/node_modules/postcss/lib/processor.es6:117:15)
    at new Processor (/usr/src/app/www/node_modules/postcss/lib/processor.es6:38:25)
    at postcss (/usr/src/app/www/node_modules/postcss/lib/postcss.es6:34:10)
    at Object.loader (/usr/src/app/www/node_modules/postcss-loader/dist/index.js:87:20)

For more details see https://gatsby.dev/issue-how-to

**Comment by malnajdi** [comment]
So i deployed it to Gatsby cloud and it seems to work. It turns out it was  a caching issue in the Gatsby Build Process. Clearing it out seems to fix it.
